server:
  port: 8083

spring:
  config:
    import:
      - "optional:file:./config.yml"
      - "optional:file:/app/config.yml"
  thymeleaf:
    cache: false
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false