server:
  port: 8081

spring:
  config:
    import: "optional:file:config.yml"
  thymeleaf:
    cache: false
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false